commit_message: New translations %original_file_name% from Crowdin
append_commit_message: 
files:
  - source: 1.18/assets*
    ignore:
      - zh-TW
    translation: '%original_path%/%file_name%.%file_extension%'
